spring.application.name=leavemanagement

# Local MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/leave_management?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1212
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Remote Clever Cloud Backup (Commented)
# spring.datasource.url=jdbc:mysql://bzhr4u0pawh8n3fxqnpv-mysql.services.clever-cloud.com:3306/bzhr4u0pawh8n3fxqnpv?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
# spring.datasource.username=uidvfn4j2atumes2
# spring.datasource.password=LhYniiwCkDFGk3oDiZzf

# Connection Pool Settings
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=120000
spring.datasource.hikari.connection-timeout=20000

# JWT Configuration
leavemanagement.app.jwtSecret=LeaveManagementSystemSecretKeyWhichNeedsToBeLongEnoughForHS512AlgorithmToWorkPerfectlyInSecurity2026
leavemanagement.app.jwtExpirationMs=86400000
